run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - gofmt
    - gosimple
    - goconst
    - misspell
    - unconvert
    - unparam
    - gocritic
    - prealloc
    - gosec
    - revive
    - exportloopref
    - nolintlint

  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment

    gocritic:
      enabled-tags:
        - performance
        - diagnostic
        - style
      disabled-checks:
        - regexpMust

    gofmt:
      simplify: true

    misspell:
      locale: US

    gosec:
      excludes:
        - G404
        - G101

    revive:
      rules:
        - name: indent-error-flow
        - name: early-return
        - name: unused-parameter
        - name: error-return
        - name: exported

issues:
  exclude-use-default: false

  exclude-rules:
    - linters: [gosec]
      text: "SQL"

    - linters: [unparam]
      text: "c \\*gin.Context"

    - linters: [unused]
      path: "tests/"

    - linters: [staticcheck]
      text: "SA5011"

output:
  formats:
    - format: colored-line-number
