run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - gofmt
    - gosimple
    - goconst
    - misspell
    - unconvert
    - unparam
    - gocritic
    - prealloc
    - gosec
    - revive
    - copyloopvar
    - nolintlint

issues:
  exclude-use-default: false

  exclude-rules:
    - linters: [gosec]
      text: "SQL"

    - linters: [unparam]
      text: "c \\*gin.Context"

    - linters: [unused]
      path: "tests/"

    - linters: [staticcheck]
      text: "SA5011"

output:
  formats:
    - format: colored-line-number
